# This is a definition file for a Github Action.
# See: https://docs.github.com/en/actions/sharing-automations/creating-actions/creating-a-docker-container-action

# We also define metadata here:
# See: https://docs.github.com/en/actions/sharing-automations/creating-actions/metadata-syntax-for-github-actions

name: 'docker-image-size-limit'
description: 'Runs docker-image-size-limit as a GitHub Action'
branding:
  icon: 'check'
  color: 'blue'

inputs:
  image:
    description: 'Image name to be checked'
    required: true
  size:
    description: 'Human readable size as the hard limit'
    required: true
  max_layers:
    description: 'The maximum number of layers in the image'
    required: false
    default: -1
  show_current_size:
    description: 'Show the current size of the image'
    required: false
    default: 'false'
  exit_zero:
    description: 'Do not fail the action even if docker image size/layers exceed size and max_layers'
    required: false
    default: 'false'
outputs:
  size:
    description: 'The output of docker-image-size-limit run'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.image }}
    - ${{ inputs.size }}
    - ${{ inputs.layers }}
    - ${{ inputs.show_current_size }}
    - ${{ inputs.exit_zero }}
